spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://192.168.1.124"
            allowedHeaders:
              - Authorization
              - Content-Type
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allow-credentials: true