spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
              - "http://127.0.0.1"
              - "http://keycloak"
#              - "http://192.168.1.12"
              - "http://127.17.0.1"
            allowedHeaders:
              - Authorization
              - Content-Type
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allow-credentials: true